# Generated by Django 4.1.5 on 2023-04-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='catalog_number',
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
