# Generated by Django 4.1.5 on 2023-04-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0002_remove_course_catalog_number_alter_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
